[target]
theater = "il-woodridge/cinemark-seven-bridges-and-imax"
movie_id = 104867
movie_name = "The Odyssey IMAX 70MM"
timezone = "America/Chicago"

[filters]
included_rows = []
excluded_rows = ["A", "B", "C", "D"]
earliest_showtime = "00:00"
latest_showtime = "23:59"
party_size = 2
earliest_date = "2026-09-09"
latest_date = "2026-09-20"
